/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.io.Serializable;
import javax.persistence.Entity;

/**
 * @author Admin
 */
@Entity
public class Administrador extends UsuarioAcademico implements Serializable {

}