/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * @author Admin
 */
@Entity
@Table(name = "administradores")
public class Administrador extends UsuarioAcademico implements Serializable {

}