/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author Admin
 */
@Entity
public class Estudiante extends UsuarioAcademico implements Serializable {


    @Basic
    private Integer reputacion;

    public Estudiante() {
        reputacion = 0;
    }

    public Estudiante(String apellido, String nombre, String dni, String correo) {
        super(apellido, nombre, dni, correo);
        reputacion = 0;
    }


    public Integer getReputacion() {
        return this.reputacion;
    }

    public void setReputacion(Integer reputacion) {
        this.reputacion = reputacion;
    }

    @Override
    public String toString() {
        return this.getApellido()+' '+ this.getNombre()+" (Estudiante)";
    }
}
