/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * @author Admin
 */
@Entity
@Table(name = "estudiantes")
public class Estudiante extends UsuarioAcademico implements Serializable {

    
    private Integer reputacion;

    public Integer getReputacion() {
        return this.reputacion;
    }

    public void setReputacion(Integer reputacion) {
        this.reputacion = reputacion;
    }

}