/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.io.Serializable;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * @author Admin
 */
@Entity
@Table(name = "materias")
public class Materia implements Serializable {

    @Id
     @SequenceGenerator(name = "sec_materias", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sec_materias")
   
    private Long id;

   
    private String materia;

    
    private String enlace;

    @ManyToMany(targetEntity = Profesor.class, mappedBy = "materias")
    private Set<Profesor> profesores;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMateria() {
        return this.materia;
    }

    public void setMateria(String materia) {
        this.materia = materia;
    }

    public String getEnlace() {
        return this.enlace;
    }

    public void setEnlace(String enlace) {
        this.enlace = enlace;
    }

    public Set<Profesor> getProfesores() {
        return this.profesores;
    }

    public void setProfesores(Set<Profesor> profesores) {
        this.profesores = profesores;
    }

}