/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.io.Serializable;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * @author Admin
 */
@Entity
public class Pregunta implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    @Basic
    private Date fechaPublicacion;

    @Basic
    private String descripcion;

    @Basic
    private String titulo;

    @OneToMany(targetEntity = Respuesta.class)
    private List<Respuesta> respuestas;

    public Pregunta() {
        respuestas= new ArrayList<>();
    }

    public Pregunta(String titulo,String desc) {
        this.titulo=titulo;
        this.descripcion=desc;
        respuestas= new ArrayList<>();
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }

    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }

    public String getPregunta() {
        return this.descripcion;
    }

    public void setPregunta(String pregunta) {
        this.descripcion = pregunta;
    }

    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public List<Respuesta> getRespuestas() {
        return this.respuestas;
    }

    public void setRespuestas(List<Respuesta> respuestas) {
        this.respuestas = respuestas;
    }

    @Override
    public String toString() {
        return titulo ;
    }
    
    public void agregarRespuesta(Respuesta respuesta){
    this.respuestas.add(respuesta);
    }

}
