/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * @author Admin
 */
@Entity
public class Profesor extends UsuarioAcademico implements Serializable {


    private Integer reputacion;
    @ManyToMany(targetEntity = Materia.class)
    private Set<Materia> materias;

    public Profesor() {
        super();
        reputacion =0;
        materias= new  HashSet();
    }

    public Profesor(String apellido, String nombre, String dni, String correo) {
        super(apellido, nombre, dni, correo);
    reputacion =0;
    materias= new HashSet();
    }


    public Set<Materia> getMaterias() {
        return this.materias;
    }

    public void setMaterias(Set<Materia> materias) {
        this.materias = materias;
    }

    public Integer getReputacion() {
        return reputacion;
    }

    public void setReputacion(Integer reputacion) {
        this.reputacion = reputacion;
    }

}