/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author Admin
 */
@Entity
public class Registrador extends Usuario implements Serializable {




    public Registrador() {
        super();
    }

    public Registrador(String apellido, String nombre, String dni, String correo, String password) {
        super(apellido, nombre, dni, correo, password);
    }
    @Override
    public String toString() {
        return this.getApellido()+' '+ this.getNombre()+" (Registrador)";
    }

}