/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.io.Serializable;
import java.sql.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import java.util.ArrayList;
import javax.persistence.ManyToOne;
/**
 * @author Admin
 */
@Entity
public class Respuesta implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;
    private String respuesta;
    @Basic
    private Integer votosPositivos;
    
    @Basic
    private Integer votosNegativos;

    @Basic
    private Date fechaPublicacion;

    @OneToMany(targetEntity = Voto.class)
    private List<Voto> votos;
    @ManyToOne
    private Estudiante estudiante;
    @ManyToOne
    private Profesor profesor;
    @ManyToOne
    private Administrador administrador;
    public Respuesta() {
        votos= new ArrayList<>();
    }

   public Respuesta(String resp, Estudiante estudiante, Profesor profesor, Administrador administrador) {
        this.respuesta = resp;
        if (estudiante != null) {
            this.estudiante = estudiante;
            this.profesor = null;
            this.administrador = null;
        } else {
            if (profesor != null) {
                this.estudiante = null;
                this.profesor = profesor;
                this.administrador = null;
            } else {
                this.estudiante = null;
                this.profesor = null;
                this.administrador = administrador;
            }
        }
    }

    public String getRespuesta() {
        return respuesta;
    }

    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getVotosPositivos() {
        return this.votosPositivos;
    }

    public void setVotosPositivos(Integer votosPositivos) {
        this.votosPositivos = votosPositivos;
    }

    public Integer getVotosNegativos() {
        return this.votosNegativos;
    }

    public void setVotosNegativos(Integer votosNegativos) {
        this.votosNegativos = votosNegativos;
    }

    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }

    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }

    public List<Voto> getVotos() {
        return this.votos;
    }

    public void setVotos(List<Voto> votos) {
        this.votos = votos;
    }

    @Override
    public String toString() {
        return respuesta;
        
    }

    public Estudiante getEstudiante() {
        return estudiante;
    }

    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    public Profesor getProfesor() {
        return profesor;
    }

    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    public Administrador getAdministrador() {
        return administrador;
    }

    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }
    public UsuarioAcademico obtenerPublicador() {
        if (this.estudiante != null) {
            return this.estudiante;
        } else {
            if (this.profesor != null) {
                return this.profesor;
            } else {
                if (this.administrador != null) {
                    return this.administrador;
                }
            }
        }
        return null;
    }


}
