/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;

/**
 * @author Admin
 */
@MappedSuperclass
public abstract class UsuarioAcademico extends Usuario {

    @Basic
    private Integer votosPositivos;

    @Basic
    private Integer votosNegativos;

    @Basic
    private Integer preguntasRealizadas;

    @Basic
    private Integer respuestasRealizadas;

    @OneToMany(targetEntity = Pregunta.class)
    private List<Pregunta> preguntas;

    @OneToMany(targetEntity = Respuesta.class)
    private List<Respuesta> respuestas;

    @OneToMany(targetEntity = Voto.class)
    private List<Voto> votos;

    public Integer getVotosPositivos() {
        return this.votosPositivos;
    }

    public void setVotosPositivos(Integer votosPositivos) {
        this.votosPositivos = votosPositivos;
    }

    public Integer getVotosNegativos() {
        return this.votosNegativos;
    }

    public void setVotosNegativos(Integer votosNegativos) {
        this.votosNegativos = votosNegativos;
    }

    public Integer getPreguntasRealizadas() {
        return this.preguntasRealizadas;
    }

    public void setPreguntasRealizadas(Integer preguntasRealizadas) {
        this.preguntasRealizadas = preguntasRealizadas;
    }

    public Integer getRespuestasRealizadas() {
        return this.respuestasRealizadas;
    }

    public void setRespuestasRealizadas(Integer respuestasRealizadas) {
        this.respuestasRealizadas = respuestasRealizadas;
    }

    public List<Pregunta> getPreguntas() {
        return this.preguntas;
    }

    public void setPreguntas(List<Pregunta> preguntas) {
        this.preguntas = preguntas;
    }

    public List<Respuesta> getRespuestas() {
        return this.respuestas;
    }

    public void setRespuestas(List<Respuesta> respuestas) {
        this.respuestas = respuestas;
    }

    public List<Voto> getVotos() {
        return this.votos;
    }

    public void setVotos(List<Voto> votos) {
        this.votos = votos;
    }

}