/**
 * This file was generated by the Jeddict
 */
package modelo;

import javax.persistence.Basic;
import javax.persistence.MappedSuperclass;

/**
 * @author Admin
 */
@MappedSuperclass
public abstract class Usuario {

    @Basic
    private String nombre;

    @Basic
    private String apellido;

    @Basic
    private String correo;

    @Basic
    private String documento;

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getDocumento() {
        return this.documento;
    }

    public void setDocumento(String documento) {
        this.documento = documento;
    }

}