/**
 * This file was generated by the Jeddict
 */
package modelo;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author Admin
 */
@Entity
public class Voto implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    @Basic
    private Boolean voto;
    @ManyToOne
    private Estudiante estudiante;
    @ManyToOne
    private Profesor profesor;
    @ManyToOne
    private Administrador administrador;
    public Voto() {
    }

    public Voto(Boolean voto, Estudiante estudiante, Profesor profesor, Administrador administrador) {
        this.administrador = administrador;
        this.estudiante = estudiante;
        this.profesor = profesor;
        this.voto = voto;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean isVoto() {
        return this.voto;
    }

    public void setVoto(Boolean voto) {
        this.voto = voto;
    }

    public Estudiante getEstudiante() {
        return estudiante;
    }

    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    public Profesor getProfesor() {
        return profesor;
    }

    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    public Administrador getAdministrador() {
        return administrador;
    }

    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }

}
